- name: Configure Docker 
  hosts: test-server
  become: true
  remote_user: ubuntu 
  become_user: root
  tasks: 
    - name: Updating apt
      command: sudo apt-get update

    - name: Install Docker
      command: sudo apt-get install -y docker.io
      ignore_errors: yes

    - name: Start Docker Service
      command: sudo systemctl start docker
      ignore_errors: yes

    - name: Deploy Docker Container
      command: docker run -itd -p 8084:8081 rutwikd/finance-me:1.0
